version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"  # adjust this if your .csproj is in a subfolder
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 40
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "deps"
